
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 17 13:35:01 CST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_atribucion = 74;
  public static final int Public = 35;
  public static final int Return = 36;
  public static final int ERROR_LiteralCero = 82;
  public static final int Mod = 68;
  public static final int Contract = 17;
  public static final int Pragma = 33;
  public static final int Break = 12;
  public static final int Coma = 52;
  public static final int Ufixed = 43;
  public static final int Op_Booleano = 71;
  public static final int Elevar = 62;
  public static final int Pipe = 48;
  public static final int Bytes = 14;
  public static final int BytesValue = 78;
  public static final int Version = 2;
  public static final int True = 42;
  public static final int Punto = 54;
  public static final int Units = 6;
  public static final int Import = 27;
  public static final int ShiftRight = 50;
  public static final int For = 22;
  public static final int Ampersand = 61;
  public static final int Div = 67;
  public static final int Mult = 66;
  public static final int DosPuntos = 58;
  public static final int Else = 20;
  public static final int Resta = 65;
  public static final int Int = 28;
  public static final int Returns = 37;
  public static final int This = 41;
  public static final int Suma = 64;
  public static final int ERROR = 83;
  public static final int LlaveCierra = 60;
  public static final int String = 39;
  public static final int Modifier = 31;
  public static final int Do = 19;
  public static final int ParentCierre = 70;
  public static final int ShiftLeft = 49;
  public static final int Private = 34;
  public static final int Op_relacional = 72;
  public static final int Payable = 32;
  public static final int Function = 24;
  public static final int Uint = 44;
  public static final int Op_Incremental = 75;
  public static final int Transac = 5;
  public static final int Mapping = 30;
  public static final int DobleAsterisco = 51;
  public static final int Continue = 16;
  public static final int ParenCuadAbre = 55;
  public static final int Byte = 13;
  public static final int If = 26;
  public static final int ERROR_Comentario = 81;
  public static final int EOF = 0;
  public static final int ERROR_Identificador = 80;
  public static final int Bool = 11;
  public static final int LlaveAbre = 59;
  public static final int From = 23;
  public static final int Address = 9;
  public static final int Struct = 40;
  public static final int Internal = 29;
  public static final int Constructor = 15;
  public static final int Hex = 25;
  public static final int Virgulilla = 63;
  public static final int PuntoComa = 53;
  public static final int ERROR_NotacionCientifica = 79;
  public static final int UintValue = 77;
  public static final int Literal = 8;
  public static final int error = 1;
  public static final int Enum = 21;
  public static final int ParenCuadCierra = 56;
  public static final int As = 10;
  public static final int Identificador = 7;
  public static final int Solidity = 38;
  public static final int ParentAbre = 69;
  public static final int Reservadas = 3;
  public static final int IntValue = 76;
  public static final int Not = 73;
  public static final int View = 46;
  public static final int SignoPregunta = 57;
  public static final int Delete = 18;
  public static final int Var = 45;
  public static final int While = 47;
  public static final int Operador = 4;
}

