
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 10 12:07:06 CST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_atribucion = 72;
  public static final int Public = 34;
  public static final int Return = 35;
  public static final int Mod = 67;
  public static final int Contract = 16;
  public static final int Pragma = 32;
  public static final int Break = 11;
  public static final int Coma = 51;
  public static final int Ufixed = 42;
  public static final int Elevar = 61;
  public static final int Op_Booleano = 70;
  public static final int Pipe = 47;
  public static final int Bytes = 13;
  public static final int BytesValue = 75;
  public static final int True = 41;
  public static final int Punto = 53;
  public static final int Units = 5;
  public static final int Import = 26;
  public static final int ShiftRight = 49;
  public static final int For = 21;
  public static final int Ampersand = 60;
  public static final int Div = 66;
  public static final int Mult = 65;
  public static final int DosPuntos = 57;
  public static final int Else = 19;
  public static final int Resta = 64;
  public static final int Int = 27;
  public static final int Returns = 36;
  public static final int This = 40;
  public static final int Suma = 63;
  public static final int ERROR = 76;
  public static final int LlaveCierra = 59;
  public static final int String = 38;
  public static final int Modifier = 30;
  public static final int Do = 18;
  public static final int ParentCierre = 69;
  public static final int ShiftLeft = 48;
  public static final int Private = 33;
  public static final int Op_relacional = 71;
  public static final int Payable = 31;
  public static final int Function = 23;
  public static final int Uint = 43;
  public static final int Transac = 4;
  public static final int Mapping = 29;
  public static final int DobleAsterisco = 50;
  public static final int Continue = 15;
  public static final int ParenCuadAbre = 54;
  public static final int Byte = 12;
  public static final int If = 25;
  public static final int EOF = 0;
  public static final int Bool = 10;
  public static final int LlaveAbre = 58;
  public static final int From = 22;
  public static final int Address = 8;
  public static final int Struct = 39;
  public static final int Internal = 28;
  public static final int Constructor = 14;
  public static final int Hex = 24;
  public static final int Virgulilla = 62;
  public static final int PuntoComa = 52;
  public static final int UintValue = 74;
  public static final int Literal = 7;
  public static final int error = 1;
  public static final int Enum = 20;
  public static final int ParenCuadCierra = 55;
  public static final int As = 9;
  public static final int Identificador = 6;
  public static final int Solidity = 37;
  public static final int ParentAbre = 68;
  public static final int Reservadas = 2;
  public static final int IntValue = 73;
  public static final int View = 45;
  public static final int SignoPregunta = 56;
  public static final int Delete = 17;
  public static final int Var = 44;
  public static final int While = 46;
  public static final int Operador = 3;
}

